stages:
  create-chatito-definitions:
    cmd: python3 translator.py -t "writer/chatito_template.chatito" -o "writer/chatito_model.chatito" -p params.yaml
    params:
    - dataset.max_ngrams
    outs:
    - writer/chatito_model.chatito
    deps:
    - writer/chatito_template.chatito
    - translator.py
  generate-phrases:
    cmd: npx chatito writer/chatito_model.chatito --format=rasa --defaultDistribution=even
      --outputPath=writer
    deps:
    - writer/chatito_model.chatito
    outs:
    - writer/rasa_dataset_testing.json
    - writer/rasa_dataset_training.json
  convert-data-to-yaml:
    cmd:
    - rasa data convert nlu -f yaml --data=writer/rasa_dataset_training.json --out=data/chatito_nlu.yml
    - rasa data convert nlu -f yaml --data=writer/rasa_dataset_testing.json --out=data/test_chatito_nlu.yml
    deps:
    - writer/rasa_dataset_testing.json
    - writer/rasa_dataset_training.json
    outs:
    - data/chatito_nlu.yml
    - data/test_chatito_nlu.yml
  train:
    cmd: rasa train --fixed-model-name nlu_model --out models --data data/chatito_nlu.yml
    outs:
    - models/nlu_model.tar.gz
    deps:
    - config.yml
    - domain.yml
    - data/chatito_nlu.yml
  test:
    cmd: rasa test nlu -m models/nlu_model.tar.gz -u data/test_chatito_nlu.yml
    deps:
    - data/test_chatito_nlu.yml
    - models/nlu_model.tar.gz
    outs:
    - results/DIETClassifier_confusion_matrix.png
    - results/DIETClassifier_errors.json
    - results/DIETClassifier_histogram.png
    - results/DIETClassifier_report.json
    - results/intent_report.json
    - results/intent_errors.json
    plots:
    - results/intent_histogram.png
    - results/intent_confusion_matrix.png
