stages:
  create-chatito-definitions:
    cmd: python3 translator.py
    outs:
    - writer/chatito_model.chatito
    deps:
    - writer/chatito_template.chatito
    - translator.py
  generate-phrases:
    cmd: npx chatito writer/chatito_model.chatito --format=rasa --defaultDistribution=even
      --outputPath=writer
    deps:
    - writer/chatito_model.chatito
    outs:
    - writer/rasa_dataset_testing.json
    - writer/rasa_dataset_training.json
  convert-data-to-yaml:
    cmd:
    - rasa data convert nlu -f yaml --data=writer/rasa_dataset_training.json --out=writer/rasa_dataset_training.yml
    - rasa data convert nlu -f yaml --data=writer/rasa_dataset_testing.json --out=writer/rasa_dataset_testing.yml
    deps:
    - writer/rasa_dataset_testing.json
    - writer/rasa_dataset_training.json
    outs:
    - writer/rasa_dataset_testing.yml
    - writer/rasa_dataset_training.yml
